import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeSwitcher } from './components/theme-switcher';
import './globals.css';
import { NextUiProvider } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} `}>
        <NextUiProvider>
          <main className="relative flex min-h-screen flex-col">
            <header className="sticky top-0 z-50 w-full border-b bg-background/50 backdrop-blur">
              <div className="container flex h-14 items-center justify-end px-20">
                <ThemeSwitcher />
              </div>
            </header>
            <div className="container flex-1 items-center border-b py-6 px-20 bg-white dark:bg-slate-950 text-black dark:text-white">
              {children}
            </div>
            <footer className="container flex h-14 items-center justify-center py-6 px-20">
              <p className="text-center text-sm leading-loose text-gray-400">
                Jesus Montiel
              </p>
            </footer>
          </main>
        </NextUiProvider>
      </body>
    </html>
  );
}
